pipeline {
  agent {
    kubernetes {
      yamlFile 'jenkins/Jenkins-agent.yaml'
      defaultContainer 'jnlp'
    }
  }

  environment {
    REGISTRY = "ayaan49"
    APP = "client"
    registryCredential = 'dockerhub'
  }

  parameters {
   booleanParam(name: 'FAST_MODE', defaultValue: false, description: 'Skip security & quality stages')
  }


  stages {

    stage('Stage 1: Checkout') {
      steps {
        echo "Checking out code..."
        git branch: 'dev', url: 'https://github.com/Ayaan49/DevSecOps-Mega-Project.git'
      }
    }

    stage('Stage 2: Compilation') {
      steps {
        echo "Checking JavaScript syntax..."
        container('nodejs') {
          dir('client') {
            sh 'find . -name "*.js" -exec node --check {} +'
          }
        }
      }
    }

    stage('Stage 3: Gitleaks Scan') {
      when {
        expression { return !params.FAST_MODE }
      }
      steps {
        echo "Scanning repo for secrets..."
        container('gitleaks') {
          sh 'gitleaks detect --source ./client --report-format=json --report-path=/home/jenkins/agent/workspace/gitleaks-report.json || true'
          echo "=== Gitleaks Report ==="
          sh 'cat /home/jenkins/agent/workspace/gitleaks-report.json'
        }
      }
    }
   

    stage('Stage 4: Code Coverage') {
      when {
        expression { return !params.FAST_MODE }
      }
      steps {
        echo "Running tests..."
        container('nodejs') {
          dir('client') {
            sh 'npm ci'
            sh 'npm test -- --coverage --watchAll=false'
          }
        }
      }
    }

    stage('Stage 5: SCA') {
      when {
        expression { return !params.FAST_MODE }
      }
      steps {
        echo "Running Dependency Check..."
        container('dependency-check') {
          dir('client') {
            withCredentials([string(credentialsId: 'NVD_API_KEY', variable: 'NVD_KEY')]) {
              sh '''
                /usr/share/dependency-check/bin/dependency-check.sh \
                  --scan . \
                  --project frontend-react \
                  --nvdApiKey $NVD_KEY \
                  --out reports \
                  --format HTML \
                  --format JSON \
                  --failOnCVSS 11
              '''
            }
          }
        }
      }
    }

    stage('Stage 6: SAST') {
      when {
        expression { return !params.FAST_MODE }
      }
      steps {
        echo "Running SonarQube..."
        container('sonar') {
        withSonarQubeEnv('mysonarqube') {
          sh '''
            sonar-scanner \
              -Dsonar.projectKey=frontend-react \
              -Dsonar.sources=client/src \
              -Dsonar.javascript.lcov.reportPaths=client/coverage/lcov.info \
              -Dsonar.dependencyCheck.jsonReportPath=client/reports/dependency-check-report.json \
              -Dsonar.dependencyCheck.htmlReportPath=client/reports/dependency-check-report.html
          '''
        }
      }
    }
  }

    stage('Stage 7: Quality Gate') {
      steps {
      when {
        expression { return !params.FAST_MODE }
      }
        script {
          timeout(time: 1, unit: 'MINUTES') {
            def qg = waitForQualityGate()
            echo "Quality Gate status: ${qg.status}"
          }
        }
      }
    }

    stage('Stage 8: Docker Image') {
      steps {
        echo "Building Docker Image..."
        container('docker-cli') {
          withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
            sh 'echo "$PASS" | docker login -u "$USER" --password-stdin'
            sh 'make client VERSION=${BUILD_NUMBER}'
          }
        }
      }
    }

    stage('Stage 9: Trivy Image Scan') {
      steps {
        echo "Scanning Docker Image for vulnerabilities..."
        container('trivy') {
          sh 'trivy image --format table -o client-image-report.html ${REGISTRY}/${APP}:${BUILD_NUMBER}'
          sh 'trivy image ${REGISTRY}/${APP}:${BUILD_NUMBER} > trivyresults.txt'
        }
      }
    }

    stage('Stage 10: Trigger CD') {
            steps {
            
                build job: 'app-gitops-updater', parameters: [
                    string(name: 'COMPONENT', value: 'client'),
                    string(name: 'TAG', value: "${env.BUILD_NUMBER}"),
                    string(name: 'ENV', value: 'dev')
                ], wait: false
            }
        }

  } // closes stages
} // closes pipeline
