sonar.projectKey=frontend-react
sonar.projectName=frontend-react
sonar.sourceEncoding=UTF-8

# Where your React code lives
sonar.sources=client/src

# Exclude build files and dependencies
sonar.exclusions=client/node_modules/**, client/build/**

# Tell Sonar where the coverage report is
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info

