apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: dev
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ayaanbordoloi25@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-credentials
              key: api-token

