apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: dev
  labels:
    service: database
spec:
  type: ExternalName
  externalName: devsecops-mysql.c0viok8km8ll.us-east-1.rds.amazonaws.com
